[base]
title = "Soliprem"
url = "https://soliprem.eu"
author = "Francesco Prem Solidoro"
email = "me@soliprem.eu"
description = ""
language = "en"
copyright = ""

[build]
content = "content"
output = "public"
assets = "assets"
deps = [
    "templates",
    "utils",
]
data = "_data"
minify = true

[build.rss]
enable = true
path = "feed.xml"

[build.sitemap]
enable = false
path = "sitemap.xml"

[build.slug]
path = "safe"
fragment = "safe"

[build.typst]
command = ["typst"]

[build.typst.svg]
extract_type = "embedded"
inline_max_size = "20KB"
dpi = 96.0

[build.css]
auto_enhance = true

[build.css.tailwind]
enable = true
command = ["tailwindcss"]
input = "./assets/styles/style.css"

[build.head]
styles = []
scripts = []
elements = ['<link rel="alternate" type="application/rss+xml" href="/feed.xml">']

[serve]
interface = "127.0.0.1"
port = 5277
watch = true

[deploy]
provider = "github"
force = false

[deploy.github]
url = "https://github.com/alice/alice.github.io"
branch = "main"

[deploy.cloudflare]
provider = "github"

[deploy.vercel]
provider = "github"

[extra]
