[base]
title = "Soliprem"
url = "https://soliprem.eu"
author = "Francesco Prem Solidoro"
email = "me@soliprem.eu"
description = ""
language = "en"
copyright = ""

[build]
path_prefix = ""
content = "content"
output = "public"
assets = "assets"
templates = "templates"
utils = "utils"
minify = true

[build.rss]
enable = true
path = "posts/index.xml"

[build.sitemap]
enable = false
path = "sitemap.xml"

[build.slug]
path = "safe"
fragment = "on"

[build.typst]
command = ["typst"]

[build.typst.svg]
extract_type = "embedded"
inline_max_size = "20KB"
dpi = 96.0

[build.tailwind]
enable = true
command = ["tailwindcss"]
input = "./assets/styles/style.css"

[build.head]
styles = []
scripts = []
elements = []

[serve]
interface = "127.0.0.1"
port = 5277
watch = true

[deploy]
provider = "github"
force = false

[deploy.github]
url = "https://github.com/alice/alice.github.io"
branch = "main"

[deploy.cloudflare]
provider = "github"

[deploy.vercel]
provider = "github"

[extra]
